[toolchain]

[features]
default = ["idl-build"]        # important
idl-build = ["anchor-lang/idl-build"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []


[programs.localnet]
cross_chain_contracts = "EdrFHSKQm93xsie3mkXPJ9k1W4MX3fM2ccWbPkVSV1ag"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"

wallet = "/home/dhruv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
