[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cross_chain_contracts = "EdrFHSKQm93xsie3mkXPJ9k1W4MX3fM2ccWbPkVSV1ag"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dhruv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
